---
- name: Instal htop
  hosts: all
  tasks:
   - name: package htop
     apt: 
      name: htop
      state: present

   - name: package zsh
     apt:
      name: zsh
      state: present

   - name: instal git
     apt:
      name: git
      state: present
...
